name: Build native rust action

inputs:
  abi:
    description: "input"
    required: yes
  target:
    description: "input"
    required: yes
  cc:
    description: "input"
    required: yes
  openssl_path:
    description: "input"
    required: yes
  timestamp:
    description: "input"
    required: yes

env:
  RUSTUP_HOME: /root/.rustup

runs:
  using: "composite"
  steps:
    - name: Cargo cache
      uses: actions/cache@v3
      id: cargo-cache
      with:
        # TODO: ref paths from cargo
        path: |
          /root/.cargo/.crates.toml
          /root/.cargo/.crates2.json
          /root/.cargo/bin/
          /root/.cargo/registry/index/            
          /root/.cargo/registry/cache/
          /root/.cargo/registry/git/db/
        key: cargo-${{ inputs.abi }}-${{ hashFiles('rust/Cargo.lock') }}
        restore-keys: cargo-${{ inputs.abi }}
    
    - name: Cargo build
      working-directory: ./rust/android
      shell: bash
      run: cargo +nightly build -Z build-std --target ${{ inputs.target }} --release
      env:
        AR: llvm-ar
        LD: ld
        RANLIB: llvm-ranlib
        CC: ${{ inputs.cc }}23-clang
        OPENSSL_DIR: /opt/openssl-3.0.5/${{ inputs.openssl_path }}
    
    - name: LLVM Strip
      working-directory: ./rust/target
      shell: bash
      run: llvm-strip ./${{ inputs.target }}/release/librust.so
    
    - name: Upload native rust
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.abi }}-${{ env.timestamp }}
        path: rust/target/${{ inputs.target }}/release/librust.so
