name: Build native rust action

inputs:
  abi:
    required: true
  target:
    required: true
  cc:
    required: true
  openssl_path:
    required: true
  timestamp:
    required: true

env:
  timestamp: ${{ inputs.timestamp }}
  RUSTUP_HOME: /root/.rustup

runs:
  using: "composite"
  steps:
    - name: Cargo cache
      uses: actions/cache@v3
      id: cargo-cache
      with:
        # TODO: ref paths from cargo
        path: |
          /root/.cargo/.crates.toml
          /root/.cargo/.crates2.json
          /root/.cargo/bin/
          /root/.cargo/registry/index/            
          /root/.cargo/registry/cache/
          /root/.cargo/registry/git/db/
        key: cargo-${{ matrix.abi }}-${{ hashFiles('rust/Cargo.lock') }}
        restore-keys: cargo-${{ matrix.abi }}
    
    - name: Cargo build
      working-directory: ./rust/android
      run: cargo +nightly build -Z build-std --target ${{ matrix.target }} --release
      env:
        AR: llvm-ar
        LD: ld
        RANLIB: llvm-ranlib
        CC: ${{ matrix.cc }}23-clang
        OPENSSL_DIR: /opt/openssl-3.0.5/${{ matrix.openssl_path }}
    
    - name: LLVM Strip
      working-directory: ./rust/target
      run: llvm-strip ./${{ matrix.target }}/release/librust.so
    
    - name: Upload native rust
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.abi }}-${{ env.timestamp }}
        path: rust/target/${{ matrix.target }}/release/librust.so
