name: AVD_setup

jobs:
  
  uses: ./.github/workflows/build.yaml

  uses: ./.github/workflows/timestamp.yaml

  name: Setup Emulator
  runs-on: macos-12
  strategy:
    matrix:
      include:
        - arch : x86
          api-level: 29
          jniLibs_dir: x86
        - arch : x86_64
          api-level: 30
          jniLibs_dir: x86_64
  needs: [build, create-timestamp]
  env:
    timestamp: ${{ needs.create-timestamp.outputs.timestamp }}
  steps:
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Gradle cache
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.3.3
        build-root-directory: ./android
        cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/dev' && github.ref != 'refs/pull/*' }}
    - name: AVD cache
      uses: actions/cache@v3
      id: avd-cache
      with: 
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd-${{ matrix.arch }}-api-${{ matrix.api-level }}      
    - name: Download native rust
      uses: actions/download-artifact@v3
      with: 
        name: ${{ matrix.arch }}-${{ env.timestamp }}
        path: android/app/src/main/jniLibs/${{ matrix.jniLibs_dir }}
    - run: yarn install
    - name: kill avd
      run: sh ./scripts/kill_emulators.sh
    - name: Create AVD and generate snapshot for caching
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        arch: ${{ matrix.arch }}
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: false
        script: echo "Generated AVD snapshot for caching."
    - name: kill react-native
      run: killall node | echo
    - name: start react-native
      run: nohup yarn react-native start > "out.yarn_react_native_start" &
