name: e2e

on:
  pull_request:
  push:

jobs:
  
  create-timestamp:
    uses: ./.github/workflows/timestamp.yaml

  build:
    uses: ./.github/workflows/build.yaml
  
  setup_emulator:
    uses: ./.github/workflows/avd.yaml
  
  e2e_test:
    name: End-to-End Test
    runs-on: macos-12
    strategy:
      matrix:
        include:
          - arch : x86
            api-level: 29
            jniLibs_dir: x86
          - arch : x86_64
            api-level: 30
            jniLibs_dir: x86_64
    needs: [create-timestamp, build]
    steps:
      - name: Run Detox Build
        run: yarn detox build -c android.emu.debug -n test
      - name: Run Detox Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: yarn detox test -c android.emu.debug -n test
