name: e2e



on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  checkout_repository:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

  setup_emulator:
    runs-on: macos-12
    steps:
      - uses: ./.github/actions/avd
  
  e2e_test:
    runs-on: macos-12
    name: End-to-End Test
    runs-on: macos-12
    strategy:
      matrix:
        include:
          - arch : x86
            api-level: 29
            jniLibs_dir: x86
          - arch : x86_64
            api-level: 30
            jniLibs_dir: x86_64
    needs: [setup_emulator]
    steps:
      - name: Run Detox Build
        run: yarn detox build -c android.emu.debug -n test
      - name: Run Detox Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: yarn detox test -c android.emu.debug -n test
